### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by ashokkafle** [ozimov/yaml-properties-maven-plugin#3]
Failed to execute goal it.ozimov:yaml-properties-maven-plugin:1.1.1:read-project-properties (default) on project dropwizard-test: A type incompatibility occurred while executing it.ozimov:yaml-properties-maven-plugin:1.1.1:read-project-properties: java.util.ArrayList cannot be cast to java.util.Map

when trying to parse yml with this format:
requestLog:
  appenders:
    - type: file
      currentLogFilename: ./logs/sample.log

**Comment by ecararus** [comment]
Same issue even in 1.1.2 
It is working for: 
name: aa
zz.tt: zz

but not working for :
name: aa
zz:
  - tt: zz

**Comment by robertotru** [comment]
Fixed by @ecararus with merged pull request (thanks a lot). 
Released version 1.1.2
