### ISSUE TITLE
Variables as property values support

### ISSUE THREAD

**Issue by thejeff77** [ozimov/yaml-properties-maven-plugin#8]
Hello, I can't tell from the docs whether or not this plugin will evaluate properties that have a variable as a value. Ex:

a = b
c = ${a}

would result in:
c = b

Perhaps add to docs, and if this is not a feature, then can you please add it?

**Comment by robertotru** [comment]
Hi @thejeff77,
thanks for asking.

This is a fork of the **properties-maven-plugin** from **mojohaus**. As you can see in their page (see http://www.mojohaus.org/properties-maven-plugin/usage.html ) the plugin resolves variables.

So the answer is yes.

**Comment by thejeff77** [comment]
Awesome. Thanks!
